version: '3.9'

services:

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: 'frontend'
    volumes:
      - ./frontend:/frontend
    networks:
      - backend_network
      - request_network
    ports:
      - '3000:80'

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: 'backend'
    volumes:
      - ./backend:/backend
    networks:
      - backend_network
    ports:
      - '8080:8080'
    depends_on:
      - frontend
      - sonarqube
      - mysql_db

  sonarqube:
    image: sonarqube:latest
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
      SONARQUBE_HOME: "/sonarqube-data"
    ports:
      - "9000:9000"
    networks:
      - backend_network
    volumes:
      - ./sonar/data:/opt/sonarqube/data

  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: java_to_dev_app_db
      MYSQL_USER: java_to_dev
      MYSQL_PASSWORD: nE5kMc7JCGNqwDQM
      MYSQL_ROOT_PASSWORD: nE5kMc7JCGNqwDQN

networks:
  request_network:

  backend_network:
    driver: bridge
