version: "3"

services:
  mysql:
    image: mysql/mysql-server:5.7
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - api_network
    environment:
      - MYSQL_ROOT_PASSWORD=springPassword
      - MYSQL_DATABASE=tqsdemo
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=demo
    ports:
      - 3306:3306

  api:
    depends_on:
      - mysql
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: 'api'
    volumes:
      - ./:/api
    networks:
      - api_network
    ports:
      - 8080:8080
    stdin_open: true
    tty: true


volumes:
  mysql:

networks:
  api_network:
    driver: bridge