name: Maven unit testing without frontend tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up JDK 17 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64

    - name: Build and run unit tests with Maven
      run: cd HW1/backend && mvn verify -Dtest=!CucumberSeleniumTests
